import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How SupportCraft AI collects, uses, and protects your data.",
};

const LAST_UPDATED = "27 June 2026";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">

      {/* Nav */}
      <header className="sticky top-0 z-50 border-b border-border/50 bg-background/90 backdrop-blur-md">
        <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5">
            <Image src="/app_icon.png" alt="SupportCraft AI" width={32} height={32} className="rounded-lg" />
            <span className="font-semibold text-base">SupportCraft AI</span>
          </Link>
          <div className="flex items-center gap-3">
            <Link href="/login"    className="hidden text-sm text-muted-foreground hover:text-foreground transition-colors sm:block">Sign in</Link>
            <Link href="/register" className="sc-btn-primary rounded-lg px-4 py-2 text-sm font-semibold">Start free trial</Link>
          </div>
        </nav>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-4xl font-bold tracking-tight mb-2">Privacy Policy</h1>
        <p className="text-sm text-muted-foreground mb-12">Last updated: {LAST_UPDATED}</p>

        <div className="prose prose-sm prose-neutral dark:prose-invert max-w-none space-y-10 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mb-3 [&_h2]:mt-8 [&_p]:leading-relaxed [&_p]:text-muted-foreground [&_ul]:space-y-1.5 [&_ul]:text-muted-foreground [&_li]:leading-relaxed">

          <p>
            Aakasa Digital (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) operates SupportCraft AI
            (&quot;the Service&quot;). This Privacy Policy explains how we collect, use, and protect
            your information when you use SupportCraft AI. By using the Service you agree to the
            practices described here.
          </p>

          <section>
            <h2>1. Information We Collect</h2>
            <p>We collect information you provide directly and data generated by your use of the Service:</p>
            <ul className="list-disc pl-5 mt-2">
              <li><strong className="text-foreground">Account information</strong> — name, email address, organisation name, and password when you register.</li>
              <li><strong className="text-foreground">Profile data</strong> — job title, phone number, timezone, and avatar you add to your profile.</li>
              <li><strong className="text-foreground">Support data</strong> — ticket content, customer records, knowledge base articles, and reply messages you create inside the platform.</li>
              <li><strong className="text-foreground">Billing data</strong> — subscription plan and PayPal subscription identifiers. We do not store raw payment card details.</li>
              <li><strong className="text-foreground">Usage data</strong> — log files, IP addresses, browser type, pages visited, and feature interactions to help us improve the Service.</li>
              <li><strong className="text-foreground">AI interaction data</strong> — prompts and responses generated through AI features, stored for quality improvement and abuse prevention.</li>
            </ul>
          </section>

          <section>
            <h2>2. How We Use Your Information</h2>
            <ul className="list-disc pl-5 mt-2">
              <li>Provide, maintain, and improve the Service.</li>
              <li>Process transactions and send related notices.</li>
              <li>Send service-related emails (account confirmations, ticket notifications, security alerts).</li>
              <li>Power AI features — ticket drafting, categorisation, and knowledge search.</li>
              <li>Monitor and analyse usage patterns to improve performance and reliability.</li>
              <li>Detect, prevent, and address fraudulent or abusive activity.</li>
              <li>Comply with legal obligations.</li>
            </ul>
            <p className="mt-3">
              We do not sell your personal information to third parties or use it to train general-purpose AI models without your explicit consent.
            </p>
          </section>

          <section>
            <h2>3. Data Sharing</h2>
            <p>We share your information only in these limited circumstances:</p>
            <ul className="list-disc pl-5 mt-2">
              <li><strong className="text-foreground">Service providers</strong> — Supabase (database and auth), OpenAI or Anthropic (AI processing), PayPal (billing), and email delivery services. Each is bound by data processing agreements.</li>
              <li><strong className="text-foreground">Legal requirements</strong> — when required by law, court order, or governmental authority.</li>
              <li><strong className="text-foreground">Business transfers</strong> — in connection with a merger, acquisition, or sale of assets, with appropriate confidentiality obligations.</li>
              <li><strong className="text-foreground">With your consent</strong> — for any other purpose you explicitly authorise.</li>
            </ul>
          </section>

          <section>
            <h2>4. Cookies and Tracking</h2>
            <p>
              We use essential cookies to maintain your authenticated session and preferences.
              We do not use advertising cookies or share browsing data with ad networks.
              You can disable cookies in your browser settings, though some features of the Service may stop working.
            </p>
          </section>

          <section>
            <h2>5. Data Retention</h2>
            <p>
              We retain your account data for as long as your account is active or as needed to provide the Service.
              When you delete your account, we remove your personal information within 30 days, except where we are
              required to retain it for legal, tax, or fraud-prevention purposes (typically no longer than 7 years).
            </p>
          </section>

          <section>
            <h2>6. Your Rights</h2>
            <p>Depending on your jurisdiction, you may have the right to:</p>
            <ul className="list-disc pl-5 mt-2">
              <li>Access the personal data we hold about you.</li>
              <li>Correct inaccurate or incomplete data.</li>
              <li>Request deletion of your data (&quot;right to be forgotten&quot;).</li>
              <li>Restrict or object to certain processing.</li>
              <li>Receive a portable copy of your data.</li>
              <li>Withdraw consent where processing is based on consent.</li>
            </ul>
            <p className="mt-3">
              To exercise these rights, email us at{" "}
              <a href="mailto:privacy@aakasadigital.com" className="text-primary hover:underline">
                privacy@aakasadigital.com
              </a>
              . We will respond within 30 days.
            </p>
          </section>

          <section>
            <h2>7. Data Security</h2>
            <p>
              We use industry-standard measures to protect your data: TLS encryption in transit,
              AES-256 encryption at rest, role-based access controls, and regular security reviews.
              No method of transmission over the internet is 100% secure. In the event of a data
              breach we will notify affected users and relevant authorities as required by applicable law.
            </p>
          </section>

          <section>
            <h2>8. International Transfers</h2>
            <p>
              SupportCraft AI is operated from Sri Lanka and uses infrastructure hosted in the United States
              and European Union. By using the Service you consent to the transfer of your data to these regions.
              We ensure appropriate safeguards are in place for any cross-border transfers.
            </p>
          </section>

          <section>
            <h2>9. Children&apos;s Privacy</h2>
            <p>
              The Service is not directed at children under 16. We do not knowingly collect personal
              information from children. If you believe a child has provided us with personal data,
              please contact us and we will delete it promptly.
            </p>
          </section>

          <section>
            <h2>10. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of material changes
              via email or a prominent notice on the Service at least 14 days before they take effect.
              Continued use of the Service after the effective date constitutes acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2>11. Contact Us</h2>
            <p>
              If you have questions or concerns about this Privacy Policy, please contact us:
            </p>
            <ul className="list-none pl-0 mt-2 not-prose space-y-1 text-sm text-muted-foreground">
              <li>Email: <a href="mailto:privacy@aakasadigital.com" className="text-primary hover:underline">privacy@aakasadigital.com</a></li>
              <li>Product: SupportCraft AI by Aakasa Digital</li>
            </ul>
          </section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border px-6 py-10">
        <div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 sm:flex-row">
          <Link href="/" className="flex items-center gap-2">
            <Image src="/app_icon.png" alt="SupportCraft AI" width={28} height={28} className="rounded-md" />
            <span className="text-sm font-semibold">SupportCraft AI</span>
            <span className="text-xs text-muted-foreground">by Aakasa Digital</span>
          </Link>
          <p className="text-xs text-muted-foreground">
            © {new Date().getFullYear()} SupportCraft AI. All rights reserved.
          </p>
          <div className="flex gap-6 text-xs text-muted-foreground">
            <Link href="/portal/login" className="hover:text-foreground transition-colors">Customer portal</Link>
            <Link href="/privacy"      className="hover:text-foreground transition-colors font-medium text-foreground">Privacy</Link>
            <Link href="/terms"        className="hover:text-foreground transition-colors">Terms</Link>
          </div>
        </div>
      </footer>

    </div>
  );
}
